version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: sudo yarn global add greenkeeper-lockfile@1
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.yarn-cache
      - run: greenkeeper-lockfile-update
      - run: yarn lint
      - run: yarn test
      - run: greenkeeper-lockfile-upload
      - deploy:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              now --token=${NOW_TOKEN} deploy --public
              now --token=${NOW_TOKEN} alias
              now --token=${NOW_TOKEN} scale canibrowse.now.sh 1
              now --token=${NOW_TOKEN} remove --yes --safe canibrowse
            fi
